---
- name: "install variables - ensure validated"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ libvirt__quiet }}"
  loop:
    - result: "{{ libvirt__packages_state in ['present', 'absent'] }}"
      description: "libvirt__packages_state in ['present', 'absent']"
      value: "{{ libvirt__packages_state }}"
    - result: "{{ libvirt__packages | type_debug == 'list' }}"
      description: "libvirt__packages is list"
      value: "{{ libvirt__packages | type_debug }}"
  loop_control:
    label: "{{ item.description }}"

- name: "packages - ensure state"
  package:
    name: "{{ libvirt__packages }}"
    state: "{{ libvirt__packages_state }}"
