---
- name: 'OS family specific variables - ensure included'
  tags: 'libvirt'
  include_vars: "{{ ansible_os_family }}.yml"

- name: 'assert tasks - ensure imported'
  tags: 'libvirt'
  import_tasks: 'assert.yml'

- name: 'packages tasks - ensure imported'
  tags: ['libvirt', 'online']
  import_tasks: 'packages.yml'
  when: libvirt__packages_manage

- name: 'config tasks - ensure imported'
  tags: 'libvirt'
  import_tasks: 'config.yml'

- name: 'services tasks - ensure imported'
  tags: 'libvirt'
  import_tasks: 'services.yml'
  when: libvirt__services_manage

- name: 'default pool tasks - ensure imported'
  tags: 'libvirt'
  import_tasks: 'pool_default.yml'
  when: libvirt__pool_default_manage
