---
- name: 'pool default dir - ensure created'
  file:
    path: '{{ libvirt__pool_default_dir }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: libvirt__pool_default_state != 'absent'

- name: 'pool default - ensure defined'
  virt_pool:
    name: 'default'
    command: 'define'
    xml: "{{ lookup('template', 'pool-default.xml.j2') }}"
  when: libvirt__pool_default_state != 'absent'

- name: 'pool default - ensure autostart'
  virt_pool:
    name: 'default'
    autostart: '{{ libvirt__pool_default_autostart }}'
  when: libvirt__pool_default_state != 'absent'

- name: 'pool default - ensure state'
  virt_pool:
    name: 'default'
    state: '{{ libvirt__pool_default_state }}'
