---
- name: "service variables - ensure validated"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ libvirt__quiet }}"
  loop:
    - result: "{{ libvirt__services_state in ['started', 'stopped'] }}"
      description: "libvirt__services_state in ['started', 'stopped']"
      value: "{{ libvirt__services_state }}"
    - result: "{{ libvirt__services_enabled is boolean }}"
      description: "libvirt__services_enabled is boolean"
      value: "{{ libvirt__services_enabled }}"
    - result: "{{ libvirt__services | type_debug == 'list' }}"
      description: "libvirt__services is list"
      value: "{{ libvirt__services | type_debug }}"
  loop_control:
    label: "{{ item.description }}"

- name: "services - ensure state"
  service:
    name: "{{ item }}"
    state: "{{ libvirt__services_state }}"
    enabled: "{{ libvirt__services_enabled }}"
  loop: "{{ libvirt__services }}"
  loop_control:
    label: "{{ item }} - ensure
      {{ libvirt__services_state }} and
      {{ libvirt__services_enabled | ternary('enabled', 'disabled') }}"
